version: 1.0.{build}
configuration: Release
before_build:
  - nuget restore filedb-studies.sln
build:
  project: filedb-studies.sln
  verbosity: minimal
  publish_nuget: false
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
